/**
 * PERSON-UX-07 — Person-bound private document service.
 *
 * Handles list, create (upload), update metadata, download, and delete
 * for PersonDocument records, enforcing:
 *   1. Tenant isolation: tenantId checked against person's tenant on every op.
 *   2. Person ownership: personId must belong to the given tenantId.
 *   3. Document-domain permission: callers pass pre-resolved permission booleans;
 *      the service does NOT re-resolve permissions — it trusts what the API layer provides.
 *   4. Private file storage: binary data stored via workspaceStorageProvider under
 *      a "person-docs/" prefix. Storage keys are opaque to clients.
 *   5. No public URL exposure: download returns a server-side stream, never a storage URL.
 *
 * Security invariant:
 *   Capacity flags (isPlayer, isTrainer, …) do NOT imply document access.
 *   Team-scope grants do NOT imply identity-document access.
 *   people.private_documents.view / .manage are the only relevant permissions.
 */

import { randomUUID } from "node:crypto";
import type { PersonDocumentCategory } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import { workspaceStorageProvider } from "@/lib/workspace/upload-storage";
import {
  validateWorkspaceUploadFile,
} from "@/lib/workspace/upload-types";
import {
  TeamDocumentValidationError,
  validateTeamDocumentUpload,
} from "@/lib/teams/team-document-validation";
import { logAction } from "@/lib/audit/log-action";

// ── Storage key scheme ─────────────────────────────────────────────────────
// The actual storage key is generated by workspaceStorageProvider.upload()
// using the tenantKey + documentId + versionNumber combination. The resulting
// blob pathname is recorded as storageKey in the PersonDocument DB record.
// All person document blobs are stored under "workspace/{tenantKey}/{documentId}/..."
// in the private Vercel Blob store, separate from public asset blobs.

// ── Error types ─────────────────────────────────────────────────────────────

export type PersonDocumentServiceErrorCode =
  | "INVALID_INPUT"
  | "PERSON_NOT_FOUND"
  | "DOCUMENT_NOT_FOUND"
  | "STORAGE_FAILURE"
  | "STORAGE_NOT_CONFIGURED";

export class PersonDocumentServiceError extends Error {
  readonly code: PersonDocumentServiceErrorCode;

  constructor(code: PersonDocumentServiceErrorCode, message: string) {
    super(message);
    this.name = "PersonDocumentServiceError";
    this.code = code;
  }
}

// ── Input/output types ───────────────────────────────────────────────────────

export type PersonDocumentRecord = {
  id: string;
  tenantId: string;
  personId: string;
  category: PersonDocumentCategory;
  title: string;
  originalFilename: string;
  mimeType: string;
  sizeBytes: number;
  issueDate: Date | null;
  expiryDate: Date | null;
  notes: string | null;
  uploadedByUserId: string | null;
  createdAt: Date;
  updatedAt: Date;
  /** Internal storage key — never sent to clients directly */
  _storageKey: string;
};

export type CreatePersonDocumentInput = {
  tenantId: string;
  personId: string;
  actorUserId: string;
  /** Resolved tenant key for storage path construction */
  tenantKey: string;
  category: PersonDocumentCategory;
  title: string;
  fileBuffer: Uint8Array;
  filename: string;
  mimeType: string;
  sizeBytes: number;
  issueDate?: Date | null;
  expiryDate?: Date | null;
  notes?: string | null;
};

export type UpdatePersonDocumentInput = {
  tenantId: string;
  personId: string;
  documentId: string;
  actorUserId: string;
  category?: PersonDocumentCategory;
  title?: string;
  issueDate?: Date | null;
  expiryDate?: Date | null;
  notes?: string | null;
};

export type DeletePersonDocumentInput = {
  tenantId: string;
  personId: string;
  documentId: string;
  actorUserId: string;
};

export type DownloadPersonDocumentInput = {
  tenantId: string;
  personId: string;
  documentId: string;
};

// ── Helpers ──────────────────────────────────────────────────────────────────

async function resolvePerson(tenantId: string, personId: string) {
  const person = await prisma.person.findUnique({
    where: { id: personId },
    select: { id: true, tenantId: true },
  });
  if (!person || person.tenantId !== tenantId) return null;
  return person;
}

async function resolveDocument(
  tenantId: string,
  personId: string,
  documentId: string,
) {
  return prisma.personDocument.findUnique({
    where: { id: documentId },
    select: {
      id: true,
      tenantId: true,
      personId: true,
      category: true,
      title: true,
      storageKey: true,
      storageUrl: true,
      originalFilename: true,
      mimeType: true,
      sizeBytes: true,
      issueDate: true,
      expiryDate: true,
      notes: true,
      uploadedByUserId: true,
      createdAt: true,
      updatedAt: true,
    },
  }).then((doc) => {
    if (!doc) return null;
    // Strict tenant + person isolation
    if (doc.tenantId !== tenantId) return null;
    if (doc.personId !== personId) return null;
    return doc;
  });
}

function toRecord(doc: Awaited<ReturnType<typeof resolveDocument>>): PersonDocumentRecord | null {
  if (!doc) return null;
  return {
    id: doc.id,
    tenantId: doc.tenantId,
    personId: doc.personId,
    category: doc.category,
    title: doc.title,
    originalFilename: doc.originalFilename,
    mimeType: doc.mimeType,
    sizeBytes: doc.sizeBytes,
    issueDate: doc.issueDate,
    expiryDate: doc.expiryDate,
    notes: doc.notes,
    uploadedByUserId: doc.uploadedByUserId,
    createdAt: doc.createdAt,
    updatedAt: doc.updatedAt,
    _storageKey: doc.storageKey,
  };
}

// ── Service functions ────────────────────────────────────────────────────────

/**
 * List all PersonDocuments for a Person (without storageKey or storageUrl).
 * Caller must have already verified people.private_documents.view permission.
 */
export async function listPersonDocuments(
  tenantId: string,
  personId: string,
): Promise<PersonDocumentRecord[]> {
  const person = await resolvePerson(tenantId, personId);
  if (!person) {
    throw new PersonDocumentServiceError("PERSON_NOT_FOUND", "Person nicht gefunden.");
  }

  const docs = await prisma.personDocument.findMany({
    where: { tenantId, personId },
    orderBy: [{ category: "asc" }, { createdAt: "desc" }],
    select: {
      id: true,
      tenantId: true,
      personId: true,
      category: true,
      title: true,
      storageKey: true,
      storageUrl: true,
      originalFilename: true,
      mimeType: true,
      sizeBytes: true,
      issueDate: true,
      expiryDate: true,
      notes: true,
      uploadedByUserId: true,
      createdAt: true,
      updatedAt: true,
    },
  });

  return docs.map((d) => ({
    id: d.id,
    tenantId: d.tenantId,
    personId: d.personId,
    category: d.category,
    title: d.title,
    originalFilename: d.originalFilename,
    mimeType: d.mimeType,
    sizeBytes: d.sizeBytes,
    issueDate: d.issueDate,
    expiryDate: d.expiryDate,
    notes: d.notes,
    uploadedByUserId: d.uploadedByUserId,
    createdAt: d.createdAt,
    updatedAt: d.updatedAt,
    _storageKey: d.storageKey,
  }));
}

/**
 * Upload a new PersonDocument.
 * Caller must have already verified people.private_documents.manage permission.
 *
 * Storage is written before DB record creation. If DB creation fails,
 * the blob is deleted on a best-effort basis.
 */
export async function createPersonDocument(
  input: CreatePersonDocumentInput,
): Promise<PersonDocumentRecord> {
  const person = await resolvePerson(input.tenantId, input.personId);
  if (!person) {
    throw new PersonDocumentServiceError("PERSON_NOT_FOUND", "Person nicht gefunden.");
  }

  const title = input.title.trim();
  if (!title) {
    throw new PersonDocumentServiceError("INVALID_INPUT", "Titel ist erforderlich.");
  }
  if (title.length > 200) {
    throw new PersonDocumentServiceError("INVALID_INPUT", "Titel darf maximal 200 Zeichen lang sein.");
  }

  let validatedFile;
  try {
    validatedFile = await validateTeamDocumentUpload({
      filename: input.filename,
      declaredContentType: input.mimeType,
      buffer: input.fileBuffer,
    });
  } catch (error) {
    if (error instanceof TeamDocumentValidationError) {
      throw new PersonDocumentServiceError(
        "INVALID_INPUT",
        error.message,
      );
    }
    throw error;
  }

  const documentId = randomUUID();
  const versionId = randomUUID().replaceAll("-", "");
  const sanitizedFilename = validatedFile.sanitizedFilename;

  // Upload to private blob store
  const uploadResult = await workspaceStorageProvider.upload({
    tenantId: input.tenantId,
    documentId,
    versionId,
    filename: sanitizedFilename,
    mimeType: validatedFile.contentType,
    buffer: input.fileBuffer,
  });

  if (!uploadResult.ok) {
    const code: PersonDocumentServiceErrorCode =
      uploadResult.code === "WORKSPACE_UPLOAD_STORAGE_NOT_CONFIGURED"
        ? "STORAGE_NOT_CONFIGURED"
        : "STORAGE_FAILURE";
    throw new PersonDocumentServiceError(code, uploadResult.error);
  }

  // Persist DB record
  try {
    const doc = await prisma.personDocument.create({
      data: {
        id: documentId,
        tenantId: input.tenantId,
        personId: input.personId,
        category: input.category,
        title,
        storageKey: uploadResult.storageKey,
        storageUrl: uploadResult.storageUrl ?? null,
        originalFilename: sanitizedFilename,
        mimeType: validatedFile.contentType,
        sizeBytes: uploadResult.sizeBytes,
        issueDate: input.issueDate ?? null,
        expiryDate: input.expiryDate ?? null,
        notes: input.notes?.trim() || null,
        uploadedByUserId: input.actorUserId,
      },
      select: {
        id: true,
        tenantId: true,
        personId: true,
        category: true,
        title: true,
        storageKey: true,
        storageUrl: true,
        originalFilename: true,
        mimeType: true,
        sizeBytes: true,
        issueDate: true,
        expiryDate: true,
        notes: true,
        uploadedByUserId: true,
        createdAt: true,
        updatedAt: true,
      },
    });

    await logAction({
      tenantId: input.tenantId,
      actorUserId: input.actorUserId,
      moduleKey: "persons",
      entityType: "PersonDocument",
      entityId: doc.id,
      action: "person_document_uploaded",
      afterJson: {
        personId: input.personId,
        category: input.category,
        mimeType: input.mimeType,
        sizeBytes: uploadResult.sizeBytes,
        hasIssueDate: !!input.issueDate,
        hasExpiryDate: !!input.expiryDate,
      },
    });

    return {
      id: doc.id,
      tenantId: doc.tenantId,
      personId: doc.personId,
      category: doc.category,
      title: doc.title,
      originalFilename: doc.originalFilename,
      mimeType: doc.mimeType,
      sizeBytes: doc.sizeBytes,
      issueDate: doc.issueDate,
      expiryDate: doc.expiryDate,
      notes: doc.notes,
      uploadedByUserId: doc.uploadedByUserId,
      createdAt: doc.createdAt,
      updatedAt: doc.updatedAt,
      _storageKey: doc.storageKey,
    };
  } catch (dbError) {
    // Best-effort blob cleanup if DB persistence fails
    await workspaceStorageProvider.delete(uploadResult.storageKey).catch(() => {});
    throw dbError;
  }
}

/**
 * Update PersonDocument metadata (no file replacement in this slice).
 * Caller must have already verified people.private_documents.manage permission.
 */
export async function updatePersonDocument(
  input: UpdatePersonDocumentInput,
): Promise<PersonDocumentRecord> {
  const existing = await resolveDocument(input.tenantId, input.personId, input.documentId);
  if (!existing) {
    throw new PersonDocumentServiceError("DOCUMENT_NOT_FOUND", "Dokument nicht gefunden.");
  }

  const title = (input.title ?? existing.title).trim();
  if (!title) {
    throw new PersonDocumentServiceError("INVALID_INPUT", "Titel ist erforderlich.");
  }

  const doc = await prisma.personDocument.update({
    where: { id: input.documentId },
    data: {
      category: input.category ?? existing.category,
      title,
      issueDate: "issueDate" in input ? input.issueDate : existing.issueDate,
      expiryDate: "expiryDate" in input ? input.expiryDate : existing.expiryDate,
      notes: "notes" in input ? (input.notes?.trim() || null) : existing.notes,
    },
    select: {
      id: true,
      tenantId: true,
      personId: true,
      category: true,
      title: true,
      storageKey: true,
      storageUrl: true,
      originalFilename: true,
      mimeType: true,
      sizeBytes: true,
      issueDate: true,
      expiryDate: true,
      notes: true,
      uploadedByUserId: true,
      createdAt: true,
      updatedAt: true,
    },
  });

  await logAction({
    tenantId: input.tenantId,
    actorUserId: input.actorUserId,
    moduleKey: "persons",
    entityType: "PersonDocument",
    entityId: doc.id,
    action: "person_document_updated",
    afterJson: {
      personId: input.personId,
      category: doc.category,
      hasIssueDate: !!doc.issueDate,
      hasExpiryDate: !!doc.expiryDate,
    },
  });

  return toRecord(doc)!;
}

/**
 * Delete a PersonDocument. Removes DB record AND blob from private storage.
 * Caller must have already verified people.private_documents.manage permission.
 */
export async function deletePersonDocument(
  input: DeletePersonDocumentInput,
): Promise<void> {
  const doc = await resolveDocument(input.tenantId, input.personId, input.documentId);
  if (!doc) {
    throw new PersonDocumentServiceError("DOCUMENT_NOT_FOUND", "Dokument nicht gefunden.");
  }

  const storageKey = doc.storageKey;

  // Delete DB record first — if blob deletion fails we don't have a dangling record
  await prisma.personDocument.delete({ where: { id: input.documentId } });

  await logAction({
    tenantId: input.tenantId,
    actorUserId: input.actorUserId,
    moduleKey: "persons",
    entityType: "PersonDocument",
    entityId: input.documentId,
    action: "person_document_deleted",
    beforeJson: {
      personId: input.personId,
      category: doc.category,
    },
  });

  // Best-effort blob deletion — do not fail if blob is already gone
  await workspaceStorageProvider.delete(storageKey).catch((err: unknown) => {
    console.warn("[person-document-service] blob deletion failed after DB delete", {
      documentId: input.documentId,
      operation: "delete",
      errorCategory:
        err instanceof Error && err.name ? err.name : "UnknownError",
    });
  });
}

/**
 * Return a server-side download stream for a PersonDocument.
 * Caller must have already verified people.private_documents.view permission.
 * Never exposes the raw storage URL to the client.
 */
export async function downloadPersonDocument(input: DownloadPersonDocumentInput) {
  const doc = await resolveDocument(input.tenantId, input.personId, input.documentId);
  if (!doc) {
    throw new PersonDocumentServiceError("DOCUMENT_NOT_FOUND", "Dokument nicht gefunden.");
  }

  const result = await workspaceStorageProvider.download({
    storageReference: doc.storageKey,
    filename: doc.originalFilename,
    mimeType: doc.mimeType,
  });

  if (!result.ok) {
    throw new PersonDocumentServiceError(
      "STORAGE_FAILURE",
      `Download fehlgeschlagen: ${result.error}`,
    );
  }

  return {
    stream: result.stream,
    filename: result.filename,
    contentType: result.contentType,
    contentDisposition: result.contentDisposition,
    sizeBytes: result.sizeBytes,
    etag: result.etag,
  };
}

/** Expose validateWorkspaceUploadFile for use in API routes */
export { validateWorkspaceUploadFile };
