import type { SceIconRegistryEntry } from "./SceIcon.types";
import {
  AddGlyph,
  CloseGlyph,
  EditGlyph,
  MoreGlyph,
  ProfileGlyph,
  SearchGlyph,
  SettingsGlyph,
} from "./glyphs/actions";
import { InfoboardGlyph, SponsoringGlyph, WebsiteGlyph } from "./glyphs/club";
import { DocumentGlyph, MessageGlyph, NotificationGlyph } from "./glyphs/communication";
import { FinanceGlyph, MembersGlyph, RoleGlyph } from "./glyphs/organisation";
import { CalendarGlyph, EventGlyph } from "./glyphs/planning";
import {
  DashboardApprovedMasterGlyph,
  MatchApprovedMasterGlyph,
  TournamentApprovedMasterGlyph,
  TrainingApprovedMasterGlyph,
  WeekPlannerApprovedMasterGlyph,
} from "./masters/approved-hero-glyphs";
import {
  AttendanceApprovedMasterGlyph,
  ClubApprovedMasterGlyph,
  CommunicationApprovedMasterGlyph,
  DocumentsApprovedMasterGlyph,
  DressingRoomApprovedMasterGlyph,
  EventsApprovedMasterGlyph,
  OrganisationApprovedMasterGlyph,
  OrgUnitApprovedMasterGlyph,
  PeopleApprovedMasterGlyph,
  PitchApprovedMasterGlyph,
  RequirementsApprovedMasterGlyph,
  ResultsApprovedMasterGlyph,
  RolesAccessApprovedMasterGlyph,
  SeasonApprovedMasterGlyph,
  StandingsApprovedMasterGlyph,
  TasksApprovedMasterGlyph,
  TeamApprovedMasterGlyph,
} from "./masters/approved-expanded-master-glyphs";
import {
  SCE_APPROVED_HERO_MASTER_ASSETS,
  SCE_APPROVED_HERO_VIEWBOX,
  SCE_APPROVED_MASTER_ASSETS,
} from "./masters/approved-hero-meta";

function entry(
  config: Omit<SceIconRegistryEntry, "name"> & { name: string },
): SceIconRegistryEntry {
  return { ...config, name: config.name };
}

export const SCE_ICON_REGISTRY = {
  dashboard: entry({
    name: "dashboard",
    category: "planning",
    label: "Dashboard",
    i18nKey: "nav.dashboard",
    purpose: "Primary planning cockpit overview.",
    aliases: ["overview"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: DashboardApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS.dashboard,
    geometrySource: "approved-master",
  }),
  calendar: entry({
    name: "calendar",
    category: "planning",
    label: "Kalender",
    i18nKey: "planning.calendar",
    purpose: "Calendar and date-centric planning surfaces.",
    aliases: ["kalender"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: CalendarGlyph,
  }),
  "week-planner": entry({
    name: "week-planner",
    category: "planning",
    label: "Wochenplaner",
    i18nKey: "planning.weekPlanner",
    purpose: "Structured weekly resource and activity planning.",
    aliases: ["wochenplaner", "weekPlanner"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: WeekPlannerApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS["week-planner"],
    geometrySource: "approved-master",
  }),
  training: entry({
    name: "training",
    category: "planning",
    label: "Training",
    i18nKey: "planning.training",
    purpose: "Training sessions and coaching/tactical planning.",
    aliases: ["trainingcenter"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TrainingApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS.training,
    geometrySource: "approved-master",
  }),
  match: entry({
    name: "match",
    category: "planning",
    label: "Spiele",
    i18nKey: "planning.matches",
    purpose: "Matches and match-day operations.",
    aliases: ["spiele", "matchcenter"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: MatchApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS.match,
    geometrySource: "approved-master",
  }),
  tournament: entry({
    name: "tournament",
    category: "planning",
    label: "Turniere",
    i18nKey: "planning.tournaments",
    purpose: "Tournaments and competitive brackets.",
    aliases: ["turniere", "tournamentcenter"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TournamentApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS.tournament,
    geometrySource: "approved-master",
  }),
  season: entry({
    name: "season",
    category: "planning",
    label: "Saison",
    i18nKey: "planning.season",
    purpose: "Season and competition period.",
    aliases: ["saison", "seasons"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: SeasonApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.season,
    geometrySource: "approved-master",
  }),
  standings: entry({
    name: "standings",
    category: "planning",
    label: "Rangliste",
    i18nKey: "planning.standings",
    purpose: "League table and ranking.",
    aliases: ["rangliste", "table"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: StandingsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.standings,
    geometrySource: "approved-master",
  }),
  results: entry({
    name: "results",
    category: "planning",
    label: "Resultate",
    i18nKey: "planning.results",
    purpose: "Completed competition results and scores.",
    aliases: ["resultate", "scores"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ResultsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.results,
    geometrySource: "approved-master",
  }),
  attendance: entry({
    name: "attendance",
    category: "planning",
    label: "Aufgebot",
    i18nKey: "planning.attendance",
    purpose: "Participation and attendance lists.",
    aliases: ["aufgebot", "participation"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: AttendanceApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.attendance,
    geometrySource: "approved-master",
  }),
  pitch: entry({
    name: "pitch",
    category: "planning",
    label: "Spielfeld",
    i18nKey: "planning.pitch",
    purpose: "Playing area and field or hall allocation.",
    aliases: ["field", "spielfeld", "hall"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: PitchApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.pitch,
    geometrySource: "approved-master",
  }),
  "dressing-room": entry({
    name: "dressing-room",
    category: "planning",
    label: "Garderobe",
    i18nKey: "planning.dressingRoom",
    purpose: "Dressing and changing room resources.",
    aliases: ["garderobe", "locker-room"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: DressingRoomApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["dressing-room"],
    geometrySource: "approved-master",
  }),
  event: entry({
    name: "event",
    category: "planning",
    label: "Veranstaltung",
    i18nKey: "planning.events",
    purpose: "Club events and activities.",
    aliases: ["veranstaltung"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: EventGlyph,
  }),
  events: entry({
    name: "events",
    category: "planning",
    label: "Veranstaltungen",
    i18nKey: "planning.events",
    purpose: "Events and veranstaltungen module.",
    aliases: ["veranstaltungen"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: EventsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.events,
    geometrySource: "approved-master",
  }),
  members: entry({
    name: "members",
    category: "organisation",
    label: "Mitglieder",
    i18nKey: "organisation.members",
    purpose: "People and membership management.",
    aliases: ["mitglieder"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: MembersGlyph,
  }),
  people: entry({
    name: "people",
    category: "organisation",
    label: "Personen",
    i18nKey: "organisation.people",
    purpose: "People and person administration.",
    aliases: ["persons", "personen"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: PeopleApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.people,
    geometrySource: "approved-master",
  }),
  team: entry({
    name: "team",
    category: "organisation",
    label: "Teams",
    i18nKey: "organisation.teams",
    purpose: "Teams and squads.",
    aliases: ["teams"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TeamApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.team,
    geometrySource: "approved-master",
  }),
  organisation: entry({
    name: "organisation",
    category: "organisation",
    label: "Organisation",
    i18nKey: "nav.organisation",
    purpose: "Organisational structure and units.",
    aliases: ["org"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: OrganisationApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.organisation,
    geometrySource: "approved-master",
  }),
  "org-unit": entry({
    name: "org-unit",
    category: "organisation",
    label: "Org-Einheit",
    i18nKey: "organisation.orgUnit",
    purpose: "Organisational unit, department, or section.",
    aliases: ["org-units", "orgUnits"],
    semanticType: "STRUCTURAL",
    status: "stable",
    Glyph: OrgUnitApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["org-unit"],
    geometrySource: "approved-master",
  }),
  role: entry({
    name: "role",
    category: "organisation",
    label: "Rollen",
    i18nKey: "organisation.roles",
    purpose: "Roles and permissions assignment.",
    aliases: ["roles", "rollen"],
    semanticType: "STRUCTURAL",
    status: "stable",
    Glyph: RoleGlyph,
  }),
  "roles-access": entry({
    name: "roles-access",
    category: "organisation",
    label: "Rollen & Zugriff",
    i18nKey: "organisation.rolesAccess",
    purpose: "Organisational roles and access control.",
    aliases: ["access", "permissions"],
    semanticType: "STRUCTURAL",
    status: "stable",
    Glyph: RolesAccessApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["roles-access"],
    geometrySource: "approved-master",
  }),
  club: entry({
    name: "club",
    category: "club",
    label: "Club",
    i18nKey: "club.identity",
    purpose: "Club identity and club administration.",
    aliases: ["verein"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ClubApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.club,
    geometrySource: "approved-master",
  }),
  tasks: entry({
    name: "tasks",
    category: "organisation",
    label: "Aufgaben",
    i18nKey: "organisation.tasks",
    purpose: "Tasks and action items.",
    aliases: ["aufgaben"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TasksApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.tasks,
    geometrySource: "approved-master",
  }),
  requirements: entry({
    name: "requirements",
    category: "organisation",
    label: "Anforderungen",
    i18nKey: "organisation.requirements",
    purpose: "Requirements and prerequisites.",
    aliases: ["anforderungen"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: RequirementsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.requirements,
    geometrySource: "approved-master",
  }),
  finance: entry({
    name: "finance",
    category: "organisation",
    label: "Finanzen",
    i18nKey: "organisation.finance",
    purpose: "Finance and billing surfaces.",
    aliases: ["billing", "finanzen"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: FinanceGlyph,
  }),
  communication: entry({
    name: "communication",
    category: "communication",
    label: "Kommunikation",
    i18nKey: "communication.module",
    purpose: "Communication, messages, and content.",
    aliases: ["kommunikation"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: CommunicationApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.communication,
    geometrySource: "approved-master",
  }),
  message: entry({
    name: "message",
    category: "communication",
    label: "Nachricht",
    i18nKey: "communication.message",
    purpose: "Messaging and conversations.",
    aliases: ["mail", "chat"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: MessageGlyph,
  }),
  notification: entry({
    name: "notification",
    category: "communication",
    label: "Benachrichtigung",
    i18nKey: "communication.notification",
    purpose: "Alerts and notifications.",
    aliases: ["bell", "alert"],
    semanticType: "STATUS",
    status: "stable",
    Glyph: NotificationGlyph,
  }),
  document: entry({
    name: "document",
    category: "communication",
    label: "Dokument",
    i18nKey: "communication.document",
    purpose: "Documents and files.",
    aliases: ["file"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: DocumentGlyph,
  }),
  documents: entry({
    name: "documents",
    category: "communication",
    label: "Dokumente",
    i18nKey: "communication.documents",
    purpose: "Document workspace and document collections.",
    aliases: ["dokumente", "workspace"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: DocumentsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.documents,
    geometrySource: "approved-master",
  }),
  website: entry({
    name: "website",
    category: "club",
    label: "Website",
    i18nKey: "club.website",
    purpose: "Public club website management.",
    aliases: [],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: WebsiteGlyph,
  }),
  infoboard: entry({
    name: "infoboard",
    category: "club",
    label: "Infoboard",
    i18nKey: "club.infoboard",
    purpose: "Infoboard and kiosk displays.",
    aliases: [],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: InfoboardGlyph,
  }),
  sponsoring: entry({
    name: "sponsoring",
    category: "club",
    label: "Sponsoring",
    i18nKey: "club.sponsoring",
    purpose: "Sponsors and partnerships.",
    aliases: ["sponsor"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: SponsoringGlyph,
  }),
  search: entry({
    name: "search",
    category: "actions",
    label: "Suche",
    purpose: "Search affordance.",
    aliases: ["find"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: SearchGlyph,
  }),
  settings: entry({
    name: "settings",
    category: "actions",
    label: "Einstellungen",
    purpose: "Settings and configuration.",
    aliases: ["gear", "cog"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: SettingsGlyph,
  }),
  profile: entry({
    name: "profile",
    category: "actions",
    label: "Profil",
    purpose: "User profile and account.",
    aliases: ["account", "user"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: ProfileGlyph,
  }),
  add: entry({
    name: "add",
    category: "actions",
    label: "Hinzufügen",
    purpose: "Create / add actions.",
    aliases: ["plus", "create"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: AddGlyph,
  }),
  edit: entry({
    name: "edit",
    category: "actions",
    label: "Bearbeiten",
    purpose: "Edit actions.",
    aliases: ["pencil"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: EditGlyph,
  }),
  close: entry({
    name: "close",
    category: "actions",
    label: "Schliessen",
    purpose: "Dismiss / close actions.",
    aliases: ["x", "dismiss"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: CloseGlyph,
  }),
  more: entry({
    name: "more",
    category: "actions",
    label: "Mehr",
    purpose: "Overflow / more actions menu.",
    aliases: ["overflow", "kebab"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: MoreGlyph,
  }),
} as const satisfies Record<string, SceIconRegistryEntry>;

export type SceIconRegistryName = keyof typeof SCE_ICON_REGISTRY;

export const SCE_ICON_REGISTRY_NAMES = Object.keys(SCE_ICON_REGISTRY) as SceIconRegistryName[];
