import type { SceIconRegistryEntry } from "./SceIcon.types";
import {
  AddGlyph,
  CloseGlyph,
  EditGlyph,
  MoreGlyph,
  ProfileGlyph,
  SearchGlyph,
} from "./glyphs/actions";
import { DocumentGlyph, MessageGlyph, NotificationGlyph } from "./glyphs/communication";
import { RoleGlyph } from "./glyphs/organisation";
import { CalendarGlyph, EventGlyph } from "./glyphs/planning";
import {
  AnalyticsApprovedMasterGlyph,
  ApprovalApprovedMasterGlyph,
  ArchiveApprovedMasterGlyph,
  AutomationApprovedMasterGlyph,
  ExportApprovedMasterGlyph,
  FormApprovedMasterGlyph,
  HistoryApprovedMasterGlyph,
  ImportApprovedMasterGlyph,
  InsightApprovedMasterGlyph,
  IntegrationApprovedMasterGlyph,
  ReportApprovedMasterGlyph,
  WorkflowApprovedMasterGlyph,
} from "./masters/approved-analytics-workflow-master-glyphs";
import {
  DashboardApprovedMasterGlyph,
  MatchApprovedMasterGlyph,
  TournamentApprovedMasterGlyph,
  TrainingApprovedMasterGlyph,
  WeekPlannerApprovedMasterGlyph,
} from "./masters/approved-hero-glyphs";
import {
  AttendanceApprovedMasterGlyph,
  ClubApprovedMasterGlyph,
  CommunicationApprovedMasterGlyph,
  DocumentsApprovedMasterGlyph,
  DressingRoomApprovedMasterGlyph,
  EventsApprovedMasterGlyph,
  OrganisationApprovedMasterGlyph,
  OrgUnitApprovedMasterGlyph,
  PeopleApprovedMasterGlyph,
  PitchApprovedMasterGlyph,
  RequirementsApprovedMasterGlyph,
  ResultsApprovedMasterGlyph,
  RolesAccessApprovedMasterGlyph,
  SeasonApprovedMasterGlyph,
  StandingsApprovedMasterGlyph,
  TasksApprovedMasterGlyph,
  TeamApprovedMasterGlyph,
} from "./masters/approved-expanded-master-glyphs";
import {
  AbsenceApprovedMasterGlyph,
  AssignmentApprovedMasterGlyph,
  AvailabilityApprovedMasterGlyph,
  CheckInApprovedMasterGlyph,
  CoachApprovedMasterGlyph,
  CommitteeBoardApprovedMasterGlyph,
  ContactApprovedMasterGlyph,
  FacilityApprovedMasterGlyph,
  GuardianParentApprovedMasterGlyph,
  InvitationApprovedMasterGlyph,
  MemberApprovedMasterGlyph,
  PartnerApprovedMasterGlyph,
  PlayerApprovedMasterGlyph,
  SponsorApprovedMasterGlyph,
  TeamManagementApprovedMasterGlyph,
  VolunteerApprovedMasterGlyph,
} from "./masters/approved-people-operations-master-glyphs";
import {
  BookingApprovedMasterGlyph,
  BudgetApprovedMasterGlyph,
  BusinessClubApprovedMasterGlyph,
  CommercialAccountApprovedMasterGlyph,
  ContractApprovedMasterGlyph,
  CostCentreApprovedMasterGlyph,
  ExpenseApprovedMasterGlyph,
  FacilityBookingApprovedMasterGlyph,
  FinanceApprovedMasterGlyph,
  PaymentApprovedMasterGlyph,
  QrInvoiceApprovedMasterGlyph,
  ReceiptApprovedMasterGlyph,
  RevenueApprovedMasterGlyph,
  SponsorshipManagementApprovedMasterGlyph,
  SubscriptionApprovedMasterGlyph,
  TransactionApprovedMasterGlyph,
} from "./masters/approved-finance-commercial-master-glyphs";
import {
  AttentionApprovedMasterGlyph,
  AuditApprovedMasterGlyph,
  BillingInvoiceApprovedMasterGlyph,
  ConflictApprovedMasterGlyph,
  InfoboardApprovedMasterGlyph,
  NewsApprovedMasterGlyph,
  NotificationsApprovedMasterGlyph,
  PlanningApprovedMasterGlyph,
  PublishApprovedMasterGlyph,
  ResourceAllocationApprovedMasterGlyph,
  SettingsApprovedMasterGlyph,
  WebsiteApprovedMasterGlyph,
} from "./masters/approved-platform-master-glyphs";
import {
  SCE_APPROVED_HERO_MASTER_ASSETS,
  SCE_APPROVED_HERO_VIEWBOX,
  SCE_APPROVED_MASTER_ASSETS,
} from "./masters/approved-hero-meta";

function entry(
  config: Omit<SceIconRegistryEntry, "name"> & { name: string },
): SceIconRegistryEntry {
  return { ...config, name: config.name };
}

export const SCE_ICON_REGISTRY = {
  dashboard: entry({
    name: "dashboard",
    category: "planning",
    label: "Dashboard",
    i18nKey: "nav.dashboard",
    purpose: "Primary planning cockpit overview.",
    aliases: ["overview"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: DashboardApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS.dashboard,
    geometrySource: "approved-master",
  }),
  calendar: entry({
    name: "calendar",
    category: "planning",
    label: "Kalender",
    i18nKey: "planning.calendar",
    purpose: "Calendar and date-centric planning surfaces.",
    aliases: ["kalender"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: CalendarGlyph,
  }),
  "week-planner": entry({
    name: "week-planner",
    category: "planning",
    label: "Wochenplaner",
    i18nKey: "planning.weekPlanner",
    purpose: "Structured weekly resource and activity planning.",
    aliases: ["wochenplaner", "weekPlanner"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: WeekPlannerApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS["week-planner"],
    geometrySource: "approved-master",
  }),
  training: entry({
    name: "training",
    category: "planning",
    label: "Training",
    i18nKey: "planning.training",
    purpose: "Training sessions and coaching/tactical planning.",
    aliases: ["trainingcenter"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TrainingApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS.training,
    geometrySource: "approved-master",
  }),
  match: entry({
    name: "match",
    category: "planning",
    label: "Spiele",
    i18nKey: "planning.matches",
    purpose: "Matches and match-day operations.",
    aliases: ["spiele", "matchcenter"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: MatchApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS.match,
    geometrySource: "approved-master",
  }),
  tournament: entry({
    name: "tournament",
    category: "planning",
    label: "Turniere",
    i18nKey: "planning.tournaments",
    purpose: "Tournaments and competitive brackets.",
    aliases: ["turniere", "tournamentcenter"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TournamentApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS.tournament,
    geometrySource: "approved-master",
  }),
  season: entry({
    name: "season",
    category: "planning",
    label: "Saison",
    i18nKey: "planning.season",
    purpose: "Season and competition period.",
    aliases: ["saison", "seasons"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: SeasonApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.season,
    geometrySource: "approved-master",
  }),
  standings: entry({
    name: "standings",
    category: "planning",
    label: "Rangliste",
    i18nKey: "planning.standings",
    purpose: "League table and ranking.",
    aliases: ["rangliste", "table"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: StandingsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.standings,
    geometrySource: "approved-master",
  }),
  results: entry({
    name: "results",
    category: "planning",
    label: "Resultate",
    i18nKey: "planning.results",
    purpose: "Completed competition results and scores.",
    aliases: ["resultate", "scores"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ResultsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.results,
    geometrySource: "approved-master",
  }),
  attendance: entry({
    name: "attendance",
    category: "planning",
    label: "Aufgebot",
    i18nKey: "planning.attendance",
    purpose: "Participation and attendance lists.",
    aliases: ["aufgebot", "participation"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: AttendanceApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.attendance,
    geometrySource: "approved-master",
  }),
  pitch: entry({
    name: "pitch",
    category: "planning",
    label: "Spielfeld",
    i18nKey: "planning.pitch",
    purpose: "Playing area and field or hall allocation.",
    aliases: ["field", "spielfeld", "hall"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: PitchApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.pitch,
    geometrySource: "approved-master",
  }),
  "dressing-room": entry({
    name: "dressing-room",
    category: "planning",
    label: "Garderobe",
    i18nKey: "planning.dressingRoom",
    purpose: "Dressing and changing room resources.",
    aliases: ["garderobe", "locker-room"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: DressingRoomApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["dressing-room"],
    geometrySource: "approved-master",
  }),
  event: entry({
    name: "event",
    category: "planning",
    label: "Veranstaltung",
    i18nKey: "planning.events",
    purpose: "Club events and activities.",
    aliases: ["veranstaltung"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: EventGlyph,
  }),
  export: entry({
    name: "export",
    category: "system",
    label: "Export",
    i18nKey: "system.export",
    purpose: "Explicit data export product or workflow.",
    aliases: ["data-export"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ExportApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.export,
    geometrySource: "approved-master",
  }),
  events: entry({
    name: "events",
    category: "planning",
    label: "Veranstaltungen",
    i18nKey: "planning.events",
    purpose: "Events and veranstaltungen module.",
    aliases: ["veranstaltungen"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: EventsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.events,
    geometrySource: "approved-master",
  }),
  members: entry({
    name: "members",
    category: "organisation",
    label: "Mitglieder",
    i18nKey: "organisation.members",
    purpose: "People and membership management.",
    aliases: ["mitglieder"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: MemberApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.member,
    geometrySource: "approved-master",
  }),
  people: entry({
    name: "people",
    category: "organisation",
    label: "Personen",
    i18nKey: "organisation.people",
    purpose: "People and person administration.",
    aliases: ["persons", "personen"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: PeopleApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.people,
    geometrySource: "approved-master",
  }),
  team: entry({
    name: "team",
    category: "organisation",
    label: "Teams",
    i18nKey: "organisation.teams",
    purpose: "Teams and squads.",
    aliases: ["teams"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TeamApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.team,
    geometrySource: "approved-master",
  }),
  organisation: entry({
    name: "organisation",
    category: "organisation",
    label: "Organisation",
    i18nKey: "nav.organisation",
    purpose: "Organisational structure and units.",
    aliases: ["org"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: OrganisationApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.organisation,
    geometrySource: "approved-master",
  }),
  "org-unit": entry({
    name: "org-unit",
    category: "organisation",
    label: "Org-Einheit",
    i18nKey: "organisation.orgUnit",
    purpose: "Organisational unit, department, or section.",
    aliases: ["org-units", "orgUnits"],
    semanticType: "STRUCTURAL",
    status: "stable",
    Glyph: OrgUnitApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["org-unit"],
    geometrySource: "approved-master",
  }),
  role: entry({
    name: "role",
    category: "organisation",
    label: "Rollen",
    i18nKey: "organisation.roles",
    purpose: "Roles and permissions assignment.",
    aliases: ["roles", "rollen"],
    semanticType: "STRUCTURAL",
    status: "stable",
    Glyph: RoleGlyph,
  }),
  "roles-access": entry({
    name: "roles-access",
    category: "organisation",
    label: "Rollen & Zugriff",
    i18nKey: "organisation.rolesAccess",
    purpose: "Organisational roles and access control.",
    aliases: ["access", "permissions"],
    semanticType: "STRUCTURAL",
    status: "stable",
    Glyph: RolesAccessApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["roles-access"],
    geometrySource: "approved-master",
  }),
  club: entry({
    name: "club",
    category: "club",
    label: "Club",
    i18nKey: "club.identity",
    purpose: "Club identity and club administration.",
    aliases: ["verein"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ClubApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.club,
    geometrySource: "approved-master",
  }),
  tasks: entry({
    name: "tasks",
    category: "organisation",
    label: "Aufgaben",
    i18nKey: "organisation.tasks",
    purpose: "Tasks and action items.",
    aliases: ["aufgaben"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TasksApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.tasks,
    geometrySource: "approved-master",
  }),
  requirements: entry({
    name: "requirements",
    category: "organisation",
    label: "Anforderungen",
    i18nKey: "organisation.requirements",
    purpose: "Requirements and prerequisites.",
    aliases: ["anforderungen"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: RequirementsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.requirements,
    geometrySource: "approved-master",
  }),
  finance: entry({
    name: "finance",
    category: "organisation",
    label: "Finanzen",
    i18nKey: "organisation.finance",
    purpose: "Finance domain and financial administration.",
    aliases: ["finanzen"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: FinanceApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.finance,
    geometrySource: "approved-master",
  }),
  booking: entry({
    name: "booking",
    category: "planning",
    label: "Buchung",
    i18nKey: "planning.booking",
    purpose: "Generic reservation or booking concept.",
    aliases: ["reservation", "buchung"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: BookingApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.booking,
    geometrySource: "approved-master",
  }),
  "facility-booking": entry({
    name: "facility-booking",
    category: "planning",
    label: "Anlagenbuchung",
    i18nKey: "planning.facilityBooking",
    purpose: "Reservation or booking of a facility or resource.",
    aliases: ["resource-booking", "anlagenbuchung"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: FacilityBookingApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["facility-booking"],
    geometrySource: "approved-master",
  }),
  payment: entry({
    name: "payment",
    category: "organisation",
    label: "Zahlung",
    i18nKey: "organisation.payment",
    purpose: "Payment operation or payment status.",
    aliases: ["zahlung"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: PaymentApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.payment,
    geometrySource: "approved-master",
  }),
  transaction: entry({
    name: "transaction",
    category: "organisation",
    label: "Transaktion",
    i18nKey: "organisation.transaction",
    purpose: "Financial transaction or money movement record.",
    aliases: ["transaktion", "money-movement"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TransactionApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.transaction,
    geometrySource: "approved-master",
  }),
  budget: entry({
    name: "budget",
    category: "organisation",
    label: "Budget",
    i18nKey: "organisation.budget",
    purpose: "Budget and budget planning.",
    aliases: ["jahresbudget"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: BudgetApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.budget,
    geometrySource: "approved-master",
  }),
  expense: entry({
    name: "expense",
    category: "organisation",
    label: "Ausgabe",
    i18nKey: "organisation.expense",
    purpose: "Outgoing financial item or expense.",
    aliases: ["ausgabe", "expenses"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ExpenseApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.expense,
    geometrySource: "approved-master",
  }),
  revenue: entry({
    name: "revenue",
    category: "organisation",
    label: "Einnahme",
    i18nKey: "organisation.revenue",
    purpose: "Incoming financial item or revenue.",
    aliases: ["einnahme", "income"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: RevenueApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.revenue,
    geometrySource: "approved-master",
  }),
  subscription: entry({
    name: "subscription",
    category: "organisation",
    label: "Abonnement",
    i18nKey: "organisation.subscription",
    purpose: "Commercial subscription or recurring billing relationship.",
    aliases: ["abonnement", "recurring-billing"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: SubscriptionApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.subscription,
    geometrySource: "approved-master",
  }),
  contract: entry({
    name: "contract",
    category: "organisation",
    label: "Vertrag",
    i18nKey: "organisation.contract",
    purpose: "Contract or commercial agreement.",
    aliases: ["vertrag", "agreement"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ContractApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.contract,
    geometrySource: "approved-master",
  }),
  "sponsorship-management": entry({
    name: "sponsorship-management",
    category: "club",
    label: "Sponsoring-Verwaltung",
    i18nKey: "club.sponsorshipManagement",
    purpose: "Administration and management of sponsorship activity.",
    aliases: ["sponsorship-admin"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: SponsorshipManagementApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["sponsorship-management"],
    geometrySource: "approved-master",
  }),
  "business-club": entry({
    name: "business-club",
    category: "club",
    label: "Business Club",
    i18nKey: "club.businessClub",
    purpose: "Business Club commercial network module.",
    aliases: ["businessclub"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: BusinessClubApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["business-club"],
    geometrySource: "approved-master",
  }),
  receipt: entry({
    name: "receipt",
    category: "organisation",
    label: "Beleg",
    i18nKey: "organisation.receipt",
    purpose: "Payment receipt or receipt document.",
    aliases: ["beleg"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ReceiptApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.receipt,
    geometrySource: "approved-master",
  }),
  "qr-invoice": entry({
    name: "qr-invoice",
    category: "organisation",
    label: "Swiss QR-Rechnung",
    i18nKey: "organisation.qrInvoice",
    purpose: "Swiss QR invoice / QR-bill concept.",
    aliases: ["qr-bill", "swiss-qr-invoice"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: QrInvoiceApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["qr-invoice"],
    geometrySource: "approved-master",
  }),
  "commercial-account": entry({
    name: "commercial-account",
    category: "organisation",
    label: "Kundenkonto",
    i18nKey: "organisation.commercialAccount",
    purpose: "Commercial customer or billing account.",
    aliases: ["customer-account", "billing-account"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: CommercialAccountApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["commercial-account"],
    geometrySource: "approved-master",
  }),
  "cost-centre": entry({
    name: "cost-centre",
    category: "organisation",
    label: "Kostenstelle",
    i18nKey: "organisation.costCentre",
    purpose: "Cost centre or financial allocation unit.",
    aliases: ["cost-center", "kostenstelle"],
    semanticType: "STRUCTURAL",
    status: "stable",
    Glyph: CostCentreApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["cost-centre"],
    geometrySource: "approved-master",
  }),
  communication: entry({
    name: "communication",
    category: "communication",
    label: "Kommunikation",
    i18nKey: "communication.module",
    purpose: "Communication, messages, and content.",
    aliases: ["kommunikation"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: CommunicationApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.communication,
    geometrySource: "approved-master",
  }),
  message: entry({
    name: "message",
    category: "communication",
    label: "Nachricht",
    i18nKey: "communication.message",
    purpose: "Messaging and conversations.",
    aliases: ["mail", "chat"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: MessageGlyph,
  }),
  notification: entry({
    name: "notification",
    category: "communication",
    label: "Benachrichtigung",
    i18nKey: "communication.notification",
    purpose: "Alerts and notifications.",
    aliases: ["bell", "alert"],
    semanticType: "STATUS",
    status: "stable",
    Glyph: NotificationGlyph,
  }),
  document: entry({
    name: "document",
    category: "communication",
    label: "Dokument",
    i18nKey: "communication.document",
    purpose: "Documents and files.",
    aliases: ["file"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: DocumentGlyph,
  }),
  documents: entry({
    name: "documents",
    category: "communication",
    label: "Dokumente",
    i18nKey: "communication.documents",
    purpose: "Document workspace and document collections.",
    aliases: ["dokumente", "workspace"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: DocumentsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.documents,
    geometrySource: "approved-master",
  }),
  attention: entry({
    name: "attention",
    category: "planning",
    label: "Aufmerksamkeit",
    i18nKey: "planning.attention",
    purpose: "Items requiring user attention or action.",
    aliases: ["needs-action"],
    semanticType: "STATUS",
    status: "stable",
    Glyph: AttentionApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.attention,
    geometrySource: "approved-master",
  }),
  audit: entry({
    name: "audit",
    category: "system",
    label: "Audit",
    i18nKey: "system.audit",
    purpose: "Audit trail, governance, and traceability.",
    aliases: ["audit-log"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: AuditApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.audit,
    geometrySource: "approved-master",
  }),
  analytics: entry({
    name: "analytics",
    category: "system",
    label: "Analytics",
    i18nKey: "system.analytics",
    purpose: "Analytics and data-analysis domain surfaces.",
    aliases: ["data-analysis"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: AnalyticsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.analytics,
    geometrySource: "approved-master",
  }),
  approval: entry({
    name: "approval",
    category: "organisation",
    label: "Approval",
    i18nKey: "organisation.approval",
    purpose: "Explicit approval, review, or decision workflow.",
    aliases: ["review-decision"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ApprovalApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.approval,
    geometrySource: "approved-master",
  }),
  archive: entry({
    name: "archive",
    category: "communication",
    label: "Archive",
    i18nKey: "communication.archive",
    purpose: "Archived records and archive lifecycle domain.",
    aliases: ["archived"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ArchiveApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.archive,
    geometrySource: "approved-master",
  }),
  automation: entry({
    name: "automation",
    category: "system",
    label: "Automation",
    i18nKey: "system.automation",
    purpose: "Automation rules and automated processes.",
    aliases: ["automated-process"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: AutomationApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.automation,
    geometrySource: "approved-master",
  }),
  "billing-invoice": entry({
    name: "billing-invoice",
    category: "organisation",
    label: "Rechnung",
    i18nKey: "organisation.billingInvoice",
    purpose: "Billing, invoices, and commercial administration.",
    aliases: ["invoice", "invoices"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: BillingInvoiceApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["billing-invoice"],
    geometrySource: "approved-master",
  }),
  conflict: entry({
    name: "conflict",
    category: "planning",
    label: "Konflikt",
    i18nKey: "planning.conflict",
    purpose: "Planning and resource allocation conflicts.",
    aliases: ["resource-conflict"],
    semanticType: "STATUS",
    status: "stable",
    Glyph: ConflictApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.conflict,
    geometrySource: "approved-master",
  }),
  news: entry({
    name: "news",
    category: "communication",
    label: "News",
    i18nKey: "communication.news",
    purpose: "News and editorial content.",
    aliases: ["editorial"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: NewsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.news,
    geometrySource: "approved-master",
  }),
  notifications: entry({
    name: "notifications",
    category: "communication",
    label: "Benachrichtigungen",
    i18nKey: "communication.notifications",
    purpose: "Notification and alert surfaces.",
    aliases: ["alerts"],
    semanticType: "STATUS",
    status: "stable",
    Glyph: NotificationsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.notifications,
    geometrySource: "approved-master",
  }),
  planning: entry({
    name: "planning",
    category: "planning",
    label: "Planung",
    i18nKey: "planning.domain",
    purpose: "Planning domain and planning workspace overview.",
    aliases: ["planung"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: PlanningApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.planning,
    geometrySource: "approved-master",
  }),
  publish: entry({
    name: "publish",
    category: "communication",
    label: "Veröffentlichen",
    i18nKey: "communication.publish",
    purpose: "Publishing and making content visible.",
    aliases: ["publishing"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: PublishApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.publish,
    geometrySource: "approved-master",
  }),
  "resource-allocation": entry({
    name: "resource-allocation",
    category: "planning",
    label: "Ressourcenzuweisung",
    i18nKey: "planning.resourceAllocation",
    purpose: "Allocation of facilities and planning resources.",
    aliases: ["allocation"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ResourceAllocationApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["resource-allocation"],
    geometrySource: "approved-master",
  }),
  website: entry({
    name: "website",
    category: "club",
    label: "Website",
    i18nKey: "club.website",
    purpose: "Public club website management.",
    aliases: [],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: WebsiteApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.website,
    geometrySource: "approved-master",
  }),
  infoboard: entry({
    name: "infoboard",
    category: "club",
    label: "Infoboard",
    i18nKey: "club.infoboard",
    purpose: "Infoboard and kiosk displays.",
    aliases: [],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: InfoboardApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.infoboard,
    geometrySource: "approved-master",
  }),
  sponsoring: entry({
    name: "sponsoring",
    category: "club",
    label: "Sponsoring",
    i18nKey: "club.sponsoring",
    purpose: "Sponsors and partnerships.",
    aliases: [],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: SponsorApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.sponsor,
    geometrySource: "approved-master",
  }),
  absence: entry({
    name: "absence",
    category: "organisation",
    label: "Abwesenheit",
    i18nKey: "organisation.absence",
    purpose: "Unavailable participant or absence status.",
    aliases: ["unavailable"],
    semanticType: "STATUS",
    status: "stable",
    Glyph: AbsenceApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.absence,
    geometrySource: "approved-master",
  }),
  assignment: entry({
    name: "assignment",
    category: "organisation",
    label: "Zuweisung",
    i18nKey: "organisation.assignment",
    purpose: "Organisational, team, or role assignment relationships.",
    aliases: ["zuweisung"],
    semanticType: "STRUCTURAL",
    status: "stable",
    Glyph: AssignmentApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.assignment,
    geometrySource: "approved-master",
  }),
  availability: entry({
    name: "availability",
    category: "organisation",
    label: "Verfügbarkeit",
    i18nKey: "organisation.availability",
    purpose: "Available participant or availability status.",
    aliases: ["verfuegbarkeit"],
    semanticType: "STATUS",
    status: "stable",
    Glyph: AvailabilityApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.availability,
    geometrySource: "approved-master",
  }),
  "check-in": entry({
    name: "check-in",
    category: "organisation",
    label: "Check-in",
    i18nKey: "organisation.checkIn",
    purpose: "Arrival and attendance check-in.",
    aliases: ["checkin", "arrival"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: CheckInApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["check-in"],
    geometrySource: "approved-master",
  }),
  coach: entry({
    name: "coach",
    category: "organisation",
    label: "Trainer",
    i18nKey: "organisation.coach",
    purpose: "Coach or trainer identity.",
    aliases: ["trainer"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: CoachApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.coach,
    geometrySource: "approved-master",
  }),
  "committee-board": entry({
    name: "committee-board",
    category: "organisation",
    label: "Vorstand",
    i18nKey: "organisation.committeeBoard",
    purpose: "Committee, board, or club leadership body.",
    aliases: ["board", "vorstand"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: CommitteeBoardApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["committee-board"],
    geometrySource: "approved-master",
  }),
  contact: entry({
    name: "contact",
    category: "organisation",
    label: "Kontakt",
    i18nKey: "organisation.contact",
    purpose: "Contact or contact record.",
    aliases: ["kontakt"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ContactApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.contact,
    geometrySource: "approved-master",
  }),
  facility: entry({
    name: "facility",
    category: "planning",
    label: "Anlage",
    i18nKey: "planning.facility",
    purpose: "Club facility or resource domain.",
    aliases: ["anlage", "facilities"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: FacilityApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.facility,
    geometrySource: "approved-master",
  }),
  "guardian-parent": entry({
    name: "guardian-parent",
    category: "organisation",
    label: "Erziehungsberechtigte",
    i18nKey: "organisation.guardianParent",
    purpose: "Parent or guardian relationship.",
    aliases: ["guardian", "parent"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: GuardianParentApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["guardian-parent"],
    geometrySource: "approved-master",
  }),
  invitation: entry({
    name: "invitation",
    category: "organisation",
    label: "Einladung",
    i18nKey: "organisation.invitation",
    purpose: "Invitation and invite flows.",
    aliases: ["einladung", "invite"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: InvitationApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.invitation,
    geometrySource: "approved-master",
  }),
  member: entry({
    name: "member",
    category: "organisation",
    label: "Mitglied",
    i18nKey: "organisation.member",
    purpose: "Club member and membership identity.",
    aliases: ["mitglied"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: MemberApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.member,
    geometrySource: "approved-master",
  }),
  partner: entry({
    name: "partner",
    category: "club",
    label: "Partner",
    i18nKey: "club.partner",
    purpose: "Partnership or business partner relationship.",
    aliases: ["partnership"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: PartnerApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.partner,
    geometrySource: "approved-master",
  }),
  player: entry({
    name: "player",
    category: "organisation",
    label: "Spieler",
    i18nKey: "organisation.player",
    purpose: "Player or athlete identity.",
    aliases: ["spieler", "athlete"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: PlayerApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.player,
    geometrySource: "approved-master",
  }),
  sponsor: entry({
    name: "sponsor",
    category: "club",
    label: "Sponsor",
    i18nKey: "club.sponsor",
    purpose: "Sponsor or sponsorship relationship.",
    aliases: [],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: SponsorApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.sponsor,
    geometrySource: "approved-master",
  }),
  "team-management": entry({
    name: "team-management",
    category: "organisation",
    label: "Teamverwaltung",
    i18nKey: "organisation.teamManagement",
    purpose: "Managing or composing a team or squad.",
    aliases: ["squad-management"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TeamManagementApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS["team-management"],
    geometrySource: "approved-master",
  }),
  volunteer: entry({
    name: "volunteer",
    category: "organisation",
    label: "Helfer",
    i18nKey: "organisation.volunteer",
    purpose: "Volunteer or club helper.",
    aliases: ["helfer", "helper"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: VolunteerApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.volunteer,
    geometrySource: "approved-master",
  }),
  form: entry({
    name: "form",
    category: "organisation",
    label: "Formular",
    i18nKey: "organisation.form",
    purpose: "Form builder, form template, or form submission domain.",
    aliases: ["form-builder"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: FormApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.form,
    geometrySource: "approved-master",
  }),
  history: entry({
    name: "history",
    category: "system",
    label: "Verlauf",
    i18nKey: "system.history",
    purpose: "Change, version, or activity history.",
    aliases: ["version-history", "activity-history"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: HistoryApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.history,
    geometrySource: "approved-master",
  }),
  import: entry({
    name: "import",
    category: "system",
    label: "Import",
    i18nKey: "system.import",
    purpose: "Explicit data import product or workflow.",
    aliases: ["data-import"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ImportApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.import,
    geometrySource: "approved-master",
  }),
  insight: entry({
    name: "insight",
    category: "system",
    label: "Insight",
    i18nKey: "system.insight",
    purpose: "Derived insight or interpretation from data.",
    aliases: ["interpretation"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: InsightApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.insight,
    geometrySource: "approved-master",
  }),
  integration: entry({
    name: "integration",
    category: "system",
    label: "Integration",
    i18nKey: "system.integration",
    purpose: "External system integration and connectors.",
    aliases: ["connectors", "integrations"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: IntegrationApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.integration,
    geometrySource: "approved-master",
  }),
  report: entry({
    name: "report",
    category: "communication",
    label: "Report",
    i18nKey: "communication.report",
    purpose: "Report artifact or reporting module.",
    aliases: ["reporting"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: ReportApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.report,
    geometrySource: "approved-master",
  }),
  workflow: entry({
    name: "workflow",
    category: "organisation",
    label: "Workflow",
    i18nKey: "organisation.workflow",
    purpose: "Explicit business or process workflow.",
    aliases: ["process-workflow"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: WorkflowApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.workflow,
    geometrySource: "approved-master",
  }),
  search: entry({
    name: "search",
    category: "actions",
    label: "Suche",
    purpose: "Search affordance.",
    aliases: ["find"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: SearchGlyph,
  }),
  settings: entry({
    name: "settings",
    category: "actions",
    label: "Einstellungen",
    purpose: "Settings and configuration.",
    aliases: ["gear", "cog"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: SettingsApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_MASTER_ASSETS.settings,
    geometrySource: "approved-master",
  }),
  profile: entry({
    name: "profile",
    category: "actions",
    label: "Profil",
    purpose: "User profile and account.",
    aliases: ["account", "user"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: ProfileGlyph,
  }),
  add: entry({
    name: "add",
    category: "actions",
    label: "Hinzufügen",
    purpose: "Create / add actions.",
    aliases: ["plus", "create"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: AddGlyph,
  }),
  edit: entry({
    name: "edit",
    category: "actions",
    label: "Bearbeiten",
    purpose: "Edit actions.",
    aliases: ["pencil"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: EditGlyph,
  }),
  close: entry({
    name: "close",
    category: "actions",
    label: "Schliessen",
    purpose: "Dismiss / close actions.",
    aliases: ["x", "dismiss"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: CloseGlyph,
  }),
  more: entry({
    name: "more",
    category: "actions",
    label: "Mehr",
    purpose: "Overflow / more actions menu.",
    aliases: ["overflow", "kebab"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: MoreGlyph,
  }),
} as const satisfies Record<string, SceIconRegistryEntry>;

export type SceIconRegistryName = keyof typeof SCE_ICON_REGISTRY;

export const SCE_ICON_REGISTRY_NAMES = Object.keys(SCE_ICON_REGISTRY) as SceIconRegistryName[];
