import type { SceIconRegistryEntry } from "./SceIcon.types";
import {
  AddGlyph,
  CloseGlyph,
  EditGlyph,
  MoreGlyph,
  ProfileGlyph,
  SearchGlyph,
  SettingsGlyph,
} from "./glyphs/actions";
import { InfoboardGlyph, SponsoringGlyph, WebsiteGlyph } from "./glyphs/club";
import { DocumentGlyph, MessageGlyph, NotificationGlyph } from "./glyphs/communication";
import {
  FinanceGlyph,
  MembersGlyph,
  OrganisationGlyph,
  RoleGlyph,
  TeamGlyph,
} from "./glyphs/organisation";
import { CalendarGlyph, EventGlyph } from "./glyphs/planning";
import {
  DashboardApprovedMasterGlyph,
  MatchApprovedMasterGlyph,
  TournamentApprovedMasterGlyph,
  TrainingApprovedMasterGlyph,
  WeekPlannerApprovedMasterGlyph,
} from "./masters/approved-hero-glyphs";
import {
  SCE_APPROVED_HERO_MASTER_ASSETS,
  SCE_APPROVED_HERO_VIEWBOX,
} from "./masters/approved-hero-meta";

function entry(
  config: Omit<SceIconRegistryEntry, "name"> & { name: string },
): SceIconRegistryEntry {
  return { ...config, name: config.name };
}

export const SCE_ICON_REGISTRY = {
  dashboard: entry({
    name: "dashboard",
    category: "planning",
    label: "Dashboard",
    i18nKey: "nav.dashboard",
    purpose: "Primary planning cockpit overview.",
    aliases: ["overview"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: DashboardApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS.dashboard,
    geometrySource: "approved-master",
  }),
  calendar: entry({
    name: "calendar",
    category: "planning",
    label: "Kalender",
    i18nKey: "planning.calendar",
    purpose: "Calendar and date-centric planning surfaces.",
    aliases: ["kalender"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: CalendarGlyph,
  }),
  "week-planner": entry({
    name: "week-planner",
    category: "planning",
    label: "Wochenplaner",
    i18nKey: "planning.weekPlanner",
    purpose: "Structured weekly resource and activity planning.",
    aliases: ["wochenplaner", "weekPlanner"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: WeekPlannerApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS["week-planner"],
    geometrySource: "approved-master",
  }),
  training: entry({
    name: "training",
    category: "planning",
    label: "Training",
    i18nKey: "planning.training",
    purpose: "Training sessions and coaching/tactical planning.",
    aliases: ["trainingcenter"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TrainingApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS.training,
    geometrySource: "approved-master",
  }),
  match: entry({
    name: "match",
    category: "planning",
    label: "Spiele",
    i18nKey: "planning.matches",
    purpose: "Matches and match-day operations.",
    aliases: ["spiele", "matchcenter"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: MatchApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS.match,
    geometrySource: "approved-master",
  }),
  tournament: entry({
    name: "tournament",
    category: "planning",
    label: "Turniere",
    i18nKey: "planning.tournaments",
    purpose: "Tournaments and competitive brackets.",
    aliases: ["turniere", "tournamentcenter"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TournamentApprovedMasterGlyph,
    viewBox: SCE_APPROVED_HERO_VIEWBOX,
    masterAssetPath: SCE_APPROVED_HERO_MASTER_ASSETS.tournament,
    geometrySource: "approved-master",
  }),
  event: entry({
    name: "event",
    category: "planning",
    label: "Veranstaltung",
    i18nKey: "planning.events",
    purpose: "Club events and activities.",
    aliases: ["veranstaltung", "events"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: EventGlyph,
  }),
  members: entry({
    name: "members",
    category: "organisation",
    label: "Mitglieder",
    i18nKey: "organisation.members",
    purpose: "People and membership management.",
    aliases: ["mitglieder", "persons"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: MembersGlyph,
  }),
  team: entry({
    name: "team",
    category: "organisation",
    label: "Teams",
    i18nKey: "organisation.teams",
    purpose: "Teams and squads.",
    aliases: ["teams"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: TeamGlyph,
  }),
  organisation: entry({
    name: "organisation",
    category: "organisation",
    label: "Organisation",
    i18nKey: "nav.organisation",
    purpose: "Organisational structure and units.",
    aliases: ["org"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: OrganisationGlyph,
  }),
  role: entry({
    name: "role",
    category: "organisation",
    label: "Rollen",
    i18nKey: "organisation.roles",
    purpose: "Roles and permissions assignment.",
    aliases: ["roles", "rollen"],
    semanticType: "STRUCTURAL",
    status: "stable",
    Glyph: RoleGlyph,
  }),
  finance: entry({
    name: "finance",
    category: "organisation",
    label: "Finanzen",
    i18nKey: "organisation.finance",
    purpose: "Finance and billing surfaces.",
    aliases: ["billing", "finanzen"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: FinanceGlyph,
  }),
  message: entry({
    name: "message",
    category: "communication",
    label: "Nachricht",
    i18nKey: "communication.message",
    purpose: "Messaging and conversations.",
    aliases: ["mail", "chat"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: MessageGlyph,
  }),
  notification: entry({
    name: "notification",
    category: "communication",
    label: "Benachrichtigung",
    i18nKey: "communication.notification",
    purpose: "Alerts and notifications.",
    aliases: ["bell", "alert"],
    semanticType: "STATUS",
    status: "stable",
    Glyph: NotificationGlyph,
  }),
  document: entry({
    name: "document",
    category: "communication",
    label: "Dokument",
    i18nKey: "communication.document",
    purpose: "Documents and files.",
    aliases: ["dokumente", "file"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: DocumentGlyph,
  }),
  website: entry({
    name: "website",
    category: "club",
    label: "Website",
    i18nKey: "club.website",
    purpose: "Public club website management.",
    aliases: [],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: WebsiteGlyph,
  }),
  infoboard: entry({
    name: "infoboard",
    category: "club",
    label: "Infoboard",
    i18nKey: "club.infoboard",
    purpose: "Infoboard and kiosk displays.",
    aliases: [],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: InfoboardGlyph,
  }),
  sponsoring: entry({
    name: "sponsoring",
    category: "club",
    label: "Sponsoring",
    i18nKey: "club.sponsoring",
    purpose: "Sponsors and partnerships.",
    aliases: ["sponsor"],
    semanticType: "DOMAIN",
    status: "stable",
    Glyph: SponsoringGlyph,
  }),
  search: entry({
    name: "search",
    category: "actions",
    label: "Suche",
    purpose: "Search affordance.",
    aliases: ["find"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: SearchGlyph,
  }),
  settings: entry({
    name: "settings",
    category: "actions",
    label: "Einstellungen",
    purpose: "Settings and configuration.",
    aliases: ["gear", "cog"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: SettingsGlyph,
  }),
  profile: entry({
    name: "profile",
    category: "actions",
    label: "Profil",
    purpose: "User profile and account.",
    aliases: ["account", "user"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: ProfileGlyph,
  }),
  add: entry({
    name: "add",
    category: "actions",
    label: "Hinzufügen",
    purpose: "Create / add actions.",
    aliases: ["plus", "create"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: AddGlyph,
  }),
  edit: entry({
    name: "edit",
    category: "actions",
    label: "Bearbeiten",
    purpose: "Edit actions.",
    aliases: ["pencil"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: EditGlyph,
  }),
  close: entry({
    name: "close",
    category: "actions",
    label: "Schliessen",
    purpose: "Dismiss / close actions.",
    aliases: ["x", "dismiss"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: CloseGlyph,
  }),
  more: entry({
    name: "more",
    category: "actions",
    label: "Mehr",
    purpose: "Overflow / more actions menu.",
    aliases: ["overflow", "kebab"],
    semanticType: "ACTION",
    status: "stable",
    Glyph: MoreGlyph,
  }),
} as const satisfies Record<string, SceIconRegistryEntry>;

export type SceIconRegistryName = keyof typeof SCE_ICON_REGISTRY;

export const SCE_ICON_REGISTRY_NAMES = Object.keys(SCE_ICON_REGISTRY) as SceIconRegistryName[];
