import { PERMISSIONS, type PermissionKey } from "@/lib/permissions/permissions";
import { TENANT_ADMINISTRATION_PERMISSIONS } from "@/lib/permissions/tenant-administration";
import { DIRECT_MESSAGE_SEND_ROUTE_PERMISSIONS } from "@/lib/communication/direct/route-access";
import { INBOX_REPLY_PERMISSIONS } from "@/lib/communication/inbox/authorization";

/** Who may stage canonical CommunicationAttachment uploads for compose surfaces. */
export const COMMUNICATION_ATTACHMENT_UPLOAD_PERMISSIONS: PermissionKey[] = [
  PERMISSIONS.REGISTRATIONS_EDIT,
  PERMISSIONS.COMMUNICATION_CLUB_SEND,
  PERMISSIONS.COMMUNICATION_TEAM_SEND,
  ...INBOX_REPLY_PERMISSIONS,
  ...DIRECT_MESSAGE_SEND_ROUTE_PERMISSIONS,
  ...TENANT_ADMINISTRATION_PERMISSIONS,
];

export const COMMUNICATION_ATTACHMENT_DOWNLOAD_PERMISSIONS: PermissionKey[] = [
  PERMISSIONS.REGISTRATIONS_VIEW,
  PERMISSIONS.REGISTRATIONS_EDIT,
  PERMISSIONS.COMMUNICATION_INBOX_VIEW,
  PERMISSIONS.COMMUNICATION_INBOX_MANAGE,
  PERMISSIONS.COMMUNICATION_INBOX_REPLY,
  PERMISSIONS.COMMUNICATION_CLUB_VIEW,
  PERMISSIONS.COMMUNICATION_CLUB_SEND,
  PERMISSIONS.COMMUNICATION_TEAM_VIEW,
  PERMISSIONS.COMMUNICATION_TEAM_SEND,
  ...TENANT_ADMINISTRATION_PERMISSIONS,
];
