export const COMMUNICATION_CENTER_INBOX_FOLDER_INBOX = "INBOX";

export const COMMUNICATION_CENTER_SYNC_BATCH_SIZE = 25;

export const COMMUNICATION_CENTER_SYNC_LEASE_MS = 120_000;

export const COMMUNICATION_CENTER_MAX_ATTACHMENT_BYTES = 10 * 1024 * 1024;

export const COMMUNICATION_CENTER_IMAP_PROVIDER = "imap";
