import {
  INBOX_MANAGE_PERMISSIONS,
  INBOX_SETTINGS_PERMISSIONS,
  INBOX_VIEW_PERMISSIONS,
} from "@/lib/communication/inbox/authorization";

export { INBOX_MANAGE_PERMISSIONS, INBOX_VIEW_PERMISSIONS, INBOX_SETTINGS_PERMISSIONS };
