/**
 * PLANNING-UX-03 — shared main + rail grid (Spiele/Turniere contract).
 */
export {
  SPIELE_WORKSPACE_MAIN_RAIL_GRID as PLANNING_WORKSPACE_MAIN_RAIL_GRID,
  SPIELE_WORKSPACE_RAIL_ASIDE as PLANNING_WORKSPACE_RAIL_ASIDE,
  SPIELE_WORKSPACE_RAIL_STACK as PLANNING_WORKSPACE_RAIL_STACK,
  SPIELE_WIDE_DESKTOP_BREAKPOINT as PLANNING_WIDE_DESKTOP_BREAKPOINT,
} from "@/components/admin/matchcenter/spiele-management-layout";
