import {
  CommunicationCenterChannel,
  CommunicationCenterConversationStatus,
  CommunicationCenterMailboxOrganization,
  CommunicationCenterMessageDirection,
  CommunicationCenterMessageStatus,
} from "@prisma/client";
import type { CommunicationCenterConversationDetailRecord } from "@/lib/communication/inbox/conversation-detail-client-dto";

/** Representative Prisma graph for a real IMAP-synced EMAIL thread on STAGE. */
export function buildRepresentativeImapEmailConversationDetailRecord(): CommunicationCenterConversationDetailRecord {
  const receivedAt = new Date("2026-09-28T09:15:00.000Z");
  const sentAt = new Date("2026-09-28T10:05:00.000Z");

  return {
    id: "conv-imap-stage-1",
    tenantId: "tenant-fca",
    mailboxId: "mailbox-1",
    channel: CommunicationCenterChannel.EMAIL,
    status: CommunicationCenterConversationStatus.OPEN,
    mailboxOrganization: CommunicationCenterMailboxOrganization.INBOX,
    mailboxOrganizationBeforeTrash: null,
    subject: "Sicherheitswarnung",
    threadRootMessageId: "msg-in-1",
    previewText: "Wichtiger Hinweis",
    lastMessageAt: sentAt,
    assignedToUserId: "user-admin",
    assignedByUserId: "user-admin",
    assignedAt: sentAt,
    contactMatchStatus: "MATCHED",
    matchedPersonId: "person-1",
    matchedSponsorContactId: null,
    platformCommunicationId: null,
    repliesAllowed: true,
    searchText: "sicherheit",
    createdAt: receivedAt,
    updatedAt: sentAt,
    matchedPerson: {
      id: "person-1",
      firstName: "Maria",
      lastName: "Muster",
      displayName: null,
      email: "maria@example.com",
    },
    matchedSponsorContact: null,
    assignedToUser: { id: "user-admin", firstName: "Club", lastName: "Admin" },
    contextLinks: [{ id: "ctx-1", contextKind: "REGISTRATION", contextId: "reg-1" }],
    readStates: [{ id: "rs-1", tenantId: "tenant-fca", conversationId: "conv-imap-stage-1", userId: "user-admin", readAt: null, starredAt: null, createdAt: receivedAt, updatedAt: receivedAt }],
    messages: [
      {
        id: "msg-in-1",
        tenantId: "tenant-fca",
        conversationId: "conv-imap-stage-1",
        mailboxId: "mailbox-1",
        folderId: "folder-inbox",
        direction: CommunicationCenterMessageDirection.INBOUND,
        status: CommunicationCenterMessageStatus.RECEIVED,
        imapUid: 178937283300006n,
        uidValidity: 1789372833n,
        providerMessageKey: "1789372833:60006",
        messageIdHeader: "<security@google.com>",
        inReplyTo: null,
        references: null,
        fromAddress: "security@google.com",
        fromDisplayName: "Google Security",
        toAddresses: ["admin@club.example", "office@club.example"],
        ccAddresses: null,
        subject: "Sicherheitswarnung",
        bodyText: "Bitte prüfen Sie Ihr Konto.",
        bodyHtmlSanitized: "<p>Bitte prüfen Sie Ihr Konto.</p>",
        remoteImagesBlocked: true,
        receivedAt,
        sentAt: null,
        outboundIdempotencyKey: null,
        providerMessageId: "1789372833:60006",
        deliveryError: null,
        createdByUserId: null,
        createdAt: receivedAt,
        updatedAt: receivedAt,
        attachmentLinks: [
          {
            id: "link-legacy",
            tenantId: "tenant-fca",
            messageId: "msg-in-1",
            attachmentId: "att-legacy",
            sortOrder: 0,
            createdAt: receivedAt,
            attachment: {
              id: "att-legacy",
              tenantId: "tenant-fca",
              storageKey: "communication-center/inbound/placeholder/pdf",
              originalFilename: "info.pdf",
              sanitizedFilename: "info.pdf",
              contentType: "application/pdf",
              sizeBytes: 1024,
              checksumSha256: "legacy",
              sourceType: "INBOUND",
              sourceDocumentId: null,
              sourceDocumentVersionId: null,
              ingestionMetadata: { legacy: true },
              lifecycleStatus: "READY",
              scanStatus: "PENDING",
              createdByUserId: null,
              createdAt: receivedAt,
            },
          },
          {
            id: "link-blob",
            tenantId: "tenant-fca",
            messageId: "msg-in-1",
            attachmentId: "att-blob",
            sortOrder: 1,
            createdAt: receivedAt,
            attachment: {
              id: "att-blob",
              tenantId: "tenant-fca",
              storageKey: "communication/tenant-fca/att-blob/report.pdf",
              originalFilename: "report.pdf",
              sanitizedFilename: "report.pdf",
              contentType: "application/pdf",
              sizeBytes: 4096,
              checksumSha256: "abc123",
              sourceType: "INBOUND",
              sourceDocumentId: null,
              sourceDocumentVersionId: null,
              ingestionMetadata: { source: "COMMUNICATION_CENTER_IMAP" },
              lifecycleStatus: "READY",
              scanStatus: "PENDING",
              createdByUserId: null,
              createdAt: receivedAt,
            },
          },
        ],
      },
      {
        id: "msg-out-1",
        tenantId: "tenant-fca",
        conversationId: "conv-imap-stage-1",
        mailboxId: "mailbox-1",
        folderId: "folder-inbox",
        direction: CommunicationCenterMessageDirection.OUTBOUND,
        status: CommunicationCenterMessageStatus.SENT,
        imapUid: null,
        uidValidity: null,
        providerMessageKey: null,
        messageIdHeader: "<reply@club.example>",
        inReplyTo: "<security@google.com>",
        references: ["<security@google.com>"],
        fromAddress: "admin@club.example",
        fromDisplayName: "FC Admin",
        toAddresses: ["security@google.com"],
        ccAddresses: null,
        subject: "Re: Sicherheitswarnung",
        bodyText: "Danke, erhalten.",
        bodyHtmlSanitized: null,
        remoteImagesBlocked: false,
        receivedAt: null,
        sentAt,
        outboundIdempotencyKey: "idem-1",
        providerMessageId: "resend-1",
        deliveryError: null,
        createdByUserId: "user-admin",
        createdAt: sentAt,
        updatedAt: sentAt,
        attachmentLinks: [],
      },
    ],
  };
}
