export const DUNNING_AUDIT_MODULE = "billing";

export const DUNNING_AUDIT_ACTIONS = {
  STARTED: "BILLING_DUNNING_STARTED",
  RESOLVED: "BILLING_DUNNING_RESOLVED",
  AUTO_SUSPENDED: "TENANT_AUTO_SUSPENDED_NON_PAYMENT",
  AUTO_REACTIVATED: "TENANT_AUTO_REACTIVATED_PAYMENT_RECOVERED",
  EXEMPTION_SET: "BILLING_DUNNING_EXEMPTION_SET",
  EXEMPTION_REMOVED: "BILLING_DUNNING_EXEMPTION_REMOVED",
} as const;
