export const NATIVE_BILLING_AUDIT_MODULE = "billing";

export const NATIVE_BILLING_AUDIT_ACTIONS = {
  CUSTOMER_CREATED: "BILLING_CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "BILLING_CUSTOMER_UPDATED",
  CUSTOMER_TENANT_LINKED: "BILLING_CUSTOMER_TENANT_LINKED",
  CUSTOMER_TENANT_UNLINKED: "BILLING_CUSTOMER_TENANT_UNLINKED",
  PROFILE_CREATED: "BILLING_PROFILE_CREATED",
  PROFILE_UPDATED: "BILLING_PROFILE_UPDATED",
  LEGAL_ENTITY_CREATED: "LEGAL_ENTITY_CREATED",
  LEGAL_ENTITY_UPDATED: "LEGAL_ENTITY_UPDATED",
  BANK_ACCOUNT_CREATED: "BILLING_BANK_ACCOUNT_CREATED",
  BANK_ACCOUNT_UPDATED: "BILLING_BANK_ACCOUNT_UPDATED",
  BANK_ACCOUNT_DEACTIVATED: "BILLING_BANK_ACCOUNT_DEACTIVATED",
} as const;
