export const SWISS_QR_COMPLIANCE_CODES = {
  INVALID_IBAN: "INVALID_IBAN",
  INVALID_QR_IBAN: "INVALID_QR_IBAN",
  INVALID_QRR: "INVALID_QRR",
  QRR_ACCOUNT_MISMATCH: "QRR_ACCOUNT_MISMATCH",
  INVALID_SCOR: "INVALID_SCOR",
  INVALID_REFERENCE_COMBINATION: "INVALID_REFERENCE_COMBINATION",
  INVALID_CREDITOR: "INVALID_CREDITOR",
  INVALID_DEBTOR: "INVALID_DEBTOR",
  INVALID_ADDRESS: "INVALID_ADDRESS",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INVALID_CURRENCY: "INVALID_CURRENCY",
  INVALID_CHARACTER: "INVALID_CHARACTER",
  FIELD_TOO_LONG: "FIELD_TOO_LONG",
  PAYLOAD_SERIALIZATION_FAILED: "PAYLOAD_SERIALIZATION_FAILED",
  QR_GENERATION_FAILED: "QR_GENERATION_FAILED",
  QR_DECODE_FAILED: "QR_DECODE_FAILED",
  QR_PAYLOAD_MISMATCH: "QR_PAYLOAD_MISMATCH",
  PDF_QR_VALIDATION_FAILED: "PDF_QR_VALIDATION_FAILED",
  UNSUPPORTED_PRODUCT_CURRENCY: "UNSUPPORTED_PRODUCT_CURRENCY",
} as const;

export type SwissQrComplianceCode =
  (typeof SWISS_QR_COMPLIANCE_CODES)[keyof typeof SWISS_QR_COMPLIANCE_CODES];
