import type { ComponentType } from "react";
import type { NavIconKey } from "@/lib/motion/nav-icon-keys";
import type { NavIconSvgProps } from "../motion-primitives";

import {
  AnbieterMappingIcon,
  DashboardIcon,
  OrganisationIcon,
  OrganisationseinheitenIcon,
  PersonenIcon,
  TeamsIcon,
  VereineIcon,
  WettkaempfeIcon,
  ZielgruppenIcon,
} from "./icons-organisation";
import {
  AnlagenRessourcenIcon,
  AdministrationIcon,
  BenutzerIcon,
  ClubEntwicklungIcon,
  DarstellungIcon,
  FinanzenIcon,
  CommercialIcon,
  BillingIcon,
  InfoboardIcon,
  InitiativenIcon,
  IntegrationenIcon,
  MaterialInventarIcon,
  MeetingsIcon,
  ProzesseAufgabenIcon,
  RollenBerechtigungenIcon,
  RollenIcon,
  SaisonsIcon,
  SponsoringIcon,
  TenantsIcon,
  UebersichtIcon,
  VorschauIcon,
  ZieleIcon,
} from "./icons-system";
import {
  AnmeldungenIcon,
  ArchivIcon,
  DokumenteIcon,
  EmailAbsenderIcon,
  KommunikationIcon,
  MatchcenterIcon,
  PlanungIcon,
  RegistrierungenIcon,
  TournamentcenterIcon,
  TrainingcenterIcon,
  VeranstaltungenIcon,
  WartelisteIcon,
  WochenplannerIcon,
} from "./icons-betrieb";
import {
  BlockBibliothekIcon,
  CmsUebersichtIcon,
  EinstellungenIcon,
  HomepageBuilderIcon,
  MedienIcon,
  NavigationIcon,
  NewsIcon,
  RedaktionIcon,
  SeitenIcon,
  VeroeffentlichungenIcon,
  WebsiteIcon,
  WiederverwendbareInhalteIcon,
} from "./icons-website";
import {
  AufgabenIcon,
  FormulareFreigabenIcon,
  HelfereinsaetzeIcon,
  MitgliederIcon,
  TrainerStaffIcon,
  VorfaelleDisziplinIcon,
} from "./icons-future-modules";

type NavIconComponent = ComponentType<Omit<NavIconSvgProps, "iconKey" | "children">>;

export const NAV_ICON_COMPONENTS: Record<NavIconKey, NavIconComponent> = {
  dashboard: DashboardIcon,
  "platform-dashboard": DashboardIcon,
  clubs: TenantsIcon,
  integrations: IntegrationenIcon,
  "access-security": AdministrationIcon,
  operations: IntegrationenIcon,
  berechtigungen: RollenBerechtigungenIcon,
  benutzerverwaltung: BenutzerIcon,
  rollenverwaltung: RollenIcon,
  organisation: OrganisationIcon,
  organisationseinheiten: OrganisationseinheitenIcon,
  zielgruppen: ZielgruppenIcon,
  teams: TeamsIcon,
  "anbieter-mapping": AnbieterMappingIcon,
  vereine: VereineIcon,
  personen: PersonenIcon,
  wettkaempfe: WettkaempfeIcon,
  website: WebsiteIcon,
  "cms-uebersicht": CmsUebersichtIcon,
  news: NewsIcon,
  seiten: SeitenIcon,
  "homepage-builder": HomepageBuilderIcon,
  navigation: NavigationIcon,
  "block-bibliothek": BlockBibliothekIcon,
  medien: MedienIcon,
  redaktion: RedaktionIcon,
  veroeffentlichungen: VeroeffentlichungenIcon,
  "wiederverwendbare-inhalte": WiederverwendbareInhalteIcon,
  einstellungen: EinstellungenIcon,
  planung: PlanungIcon,
  trainingcenter: TrainingcenterIcon,
  matchcenter: MatchcenterIcon,
  tournamentcenter: TournamentcenterIcon,
  veranstaltungen: VeranstaltungenIcon,
  wochenplanner: WochenplannerIcon,
  dokumente: DokumenteIcon,
  anmeldungen: AnmeldungenIcon,
  registrierungen: RegistrierungenIcon,
  warteliste: WartelisteIcon,
  archiv: ArchivIcon,
  kommunikation: KommunikationIcon,
  "email-absender": EmailAbsenderIcon,
  infoboard: InfoboardIcon,
  uebersicht: UebersichtIcon,
  vorschau: VorschauIcon,
  meetings: MeetingsIcon,
  "club-entwicklung": ClubEntwicklungIcon,
  ziele: ZieleIcon,
  initiativen: InitiativenIcon,
  "prozesse-aufgaben": ProzesseAufgabenIcon,
  "material-inventar": MaterialInventarIcon,
  finanzen: FinanzenIcon,
  commercial: CommercialIcon,
  billing: BillingIcon,
  sponsoring: SponsoringIcon,
  mitglieder: MitgliederIcon,
  aufgaben: AufgabenIcon,
  helfereinsaetze: HelfereinsaetzeIcon,
  "trainer-staff": TrainerStaffIcon,
  "formulare-freigaben": FormulareFreigabenIcon,
  "vorfaelle-disziplin": VorfaelleDisziplinIcon,
  administration: AdministrationIcon,
  "rollen-berechtigungen": RollenBerechtigungenIcon,
  saisons: SaisonsIcon,
  "anlagen-ressourcen": AnlagenRessourcenIcon,
  darstellung: DarstellungIcon,
  benutzer: BenutzerIcon,
  rollen: RollenIcon,
  tenants: TenantsIcon,
  integrationen: IntegrationenIcon,
};

export function getNavIconComponent(key: NavIconKey): NavIconComponent {
  return NAV_ICON_COMPONENTS[key];
}
