/**
 * WORKSPACE-08-01 — canonical workspace governance action taxonomy.
 */

export const WORKSPACE_GOVERNANCE_MODULE_KEY = "workspace" as const;

/** Workspace resource mutations and access events (W08-01). */
export const WorkspaceAuditAction = {
  FOLDER_CREATED: "WORKSPACE_FOLDER_CREATED",
  FOLDER_RENAMED: "WORKSPACE_FOLDER_RENAMED",
  FOLDER_MOVED: "WORKSPACE_FOLDER_MOVED",
  FOLDER_ARCHIVED: "WORKSPACE_FOLDER_ARCHIVED",
  FOLDER_RESTORED_FROM_ARCHIVE: "WORKSPACE_FOLDER_RESTORED_FROM_ARCHIVE",
  FOLDER_TRASHED: "WORKSPACE_FOLDER_TRASHED",
  FOLDER_RESTORED_FROM_TRASH: "WORKSPACE_FOLDER_RESTORED_FROM_TRASH",
  FOLDER_PERMANENTLY_DELETED: "WORKSPACE_FOLDER_PERMANENTLY_DELETED",

  DOCUMENT_VERSION_CREATED: "WORKSPACE_DOCUMENT_VERSION_CREATED",
  DOCUMENT_VERSION_RESTORED: "WORKSPACE_DOCUMENT_VERSION_RESTORED",
  DOCUMENT_ARCHIVED: "WORKSPACE_DOCUMENT_ARCHIVED",
  DOCUMENT_RESTORED_FROM_ARCHIVE: "WORKSPACE_DOCUMENT_RESTORED_FROM_ARCHIVE",
  DOCUMENT_TRASHED: "WORKSPACE_DOCUMENT_TRASHED",
  DOCUMENT_RESTORED_FROM_TRASH: "WORKSPACE_DOCUMENT_RESTORED_FROM_TRASH",
  DOCUMENT_PERMANENTLY_DELETED: "WORKSPACE_DOCUMENT_PERMANENTLY_DELETED",
  DOCUMENT_PERMANENT_DELETE_BLOCKED: "WORKSPACE_DOCUMENT_PERMANENT_DELETE_BLOCKED",
  FOLDER_PERMANENT_DELETE_BLOCKED: "WORKSPACE_FOLDER_PERMANENT_DELETE_BLOCKED",

  ACCESS_POLICY_CHANGED: "WORKSPACE_ACCESS_POLICY_CHANGED",
  ACCESS_DENIED: "WORKSPACE_ACCESS_DENIED",
  DOWNLOAD_DENIED: "WORKSPACE_DOWNLOAD_DENIED",
  PREVIEW_DENIED: "WORKSPACE_PREVIEW_DENIED",

  BREAK_GLASS_ACTIVATED: "WORKSPACE_BREAK_GLASS_ACTIVATED",
  BREAK_GLASS_USED: "WORKSPACE_BREAK_GLASS_USED",
  BREAK_GLASS_ENDED: "WORKSPACE_BREAK_GLASS_ENDED",
  BREAK_GLASS_REVOKED: "WORKSPACE_BREAK_GLASS_REVOKED",

  GOVERNANCE_HOLD_CREATED: "WORKSPACE_GOVERNANCE_HOLD_CREATED",
  GOVERNANCE_HOLD_RELEASED: "WORKSPACE_GOVERNANCE_HOLD_RELEASED",
  PURGE_COMPLETED: "WORKSPACE_PURGE_COMPLETED",
  PURGE_BLOCKED: "WORKSPACE_PURGE_BLOCKED",
  RETENTION_POLICY_CHANGED: "WORKSPACE_RETENTION_POLICY_CHANGED",

  SCAN_REQUESTED: "WORKSPACE_SCAN_REQUESTED",
  SCAN_STARTED: "WORKSPACE_SCAN_STARTED",
  SCAN_CLEAN: "WORKSPACE_SCAN_CLEAN",
  SCAN_INFECTED: "WORKSPACE_SCAN_INFECTED",
  SCAN_FAILED: "WORKSPACE_SCAN_FAILED",
  SCAN_BLOCKED: "WORKSPACE_SCAN_BLOCKED",
  FILE_DELIVERY_BLOCKED: "WORKSPACE_FILE_DELIVERY_BLOCKED",

  BACKGROUND_JOB_CREATED: "WORKSPACE_BACKGROUND_JOB_CREATED",
  BACKGROUND_JOB_RETRIED: "WORKSPACE_BACKGROUND_JOB_RETRIED",
  BACKGROUND_JOB_DEAD: "WORKSPACE_BACKGROUND_JOB_DEAD",

  SUBTREE_OPERATION_REQUESTED: "WORKSPACE_SUBTREE_OPERATION_REQUESTED",
  SUBTREE_OPERATION_STARTED: "WORKSPACE_SUBTREE_OPERATION_STARTED",
  SUBTREE_OPERATION_BLOCKED: "WORKSPACE_SUBTREE_OPERATION_BLOCKED",
  SUBTREE_OPERATION_COMPLETED: "WORKSPACE_SUBTREE_OPERATION_COMPLETED",
  SUBTREE_OPERATION_FAILED: "WORKSPACE_SUBTREE_OPERATION_FAILED",

  PURGE_RETRY_SCHEDULED: "WORKSPACE_PURGE_RETRY_SCHEDULED",
} as const;

export type WorkspaceAuditActionValue =
  (typeof WorkspaceAuditAction)[keyof typeof WorkspaceAuditAction];

/** Reserved for W08-02+ — not emitted in W08-01. */
export const WorkspaceAuditFutureAction = {
  GOVERNANCE_OVERRIDE: "WORKSPACE_GOVERNANCE_OVERRIDE",
  /** @deprecated Reserved alias — use WorkspaceAuditAction.BREAK_GLASS_* */
  BREAK_GLASS_START: "WORKSPACE_BREAK_GLASS_START",
  /** @deprecated Reserved alias — use WorkspaceAuditAction.BREAK_GLASS_* */
  BREAK_GLASS_END: "WORKSPACE_BREAK_GLASS_END",
  RETENTION_POLICY_CHANGED: "WORKSPACE_RETENTION_POLICY_CHANGED",
  HOLD_APPLIED: "WORKSPACE_HOLD_APPLIED",
  HOLD_RELEASED: "WORKSPACE_HOLD_RELEASED",
  PURGE_EXECUTED: "WORKSPACE_PURGE_EXECUTED",
  SCAN_STATE_CHANGED: "WORKSPACE_SCAN_STATE_CHANGED",
  INFECTED_FILE_ACTION: "WORKSPACE_INFECTED_FILE_ACTION",
} as const;

export const W07_REFERENCE_AUDIT_ACTIONS = [
  "TASK_DOCUMENT_LINKED",
  "TASK_DOCUMENT_UNLINKED",
  "REQUIREMENT_DOCUMENT_LINKED",
  "REQUIREMENT_DOCUMENT_UNLINKED",
] as const;

const LEGACY_WORKSPACE_ACTION_ALIASES: Record<string, WorkspaceAuditActionValue> = {
  PRIVATE_DOCUMENT_UPLOADED: WorkspaceAuditAction.DOCUMENT_VERSION_CREATED,
  PRIVATE_DOCUMENT_ARCHIVED: WorkspaceAuditAction.DOCUMENT_ARCHIVED,
  PRIVATE_DOCUMENT_RESTORED: WorkspaceAuditAction.DOCUMENT_RESTORED_FROM_ARCHIVE,
  PRIVATE_DOCUMENT_TRASHED: WorkspaceAuditAction.DOCUMENT_TRASHED,
  PRIVATE_DOCUMENT_RESTORED_FROM_TRASH: WorkspaceAuditAction.DOCUMENT_RESTORED_FROM_TRASH,
  PRIVATE_DOCUMENT_CONTAINER_MOVED: WorkspaceAuditAction.FOLDER_MOVED,
  PRIVATE_DOCUMENT_CONTAINER_DELETED: WorkspaceAuditAction.FOLDER_PERMANENTLY_DELETED,
};

export function normalizeWorkspaceAuditActionLabel(
  action: string,
): WorkspaceAuditActionValue | string {
  return LEGACY_WORKSPACE_ACTION_ALIASES[action] ?? action;
}

export function isWorkspaceGovernanceModuleKey(moduleKey: string): boolean {
  return moduleKey === WORKSPACE_GOVERNANCE_MODULE_KEY;
}
